#!/usr/bin/env python
"""Hybrid answers and answer length, measured on TWO instruments at once.

    python scripts/sweep_hybrid.py

The Phase 3 mistake, and the correction
---------------------------------------
Phase 3 chose a prompt template using one instrument — cosine similarity to the
source excerpt — for a decision spanning two scoring dimensions. That instrument
is *right* for groundedness (25%, and the grader measures it by automated
semantic similarity) and *wrong* for answer accuracy (25%, which rewards
answering the question). Extraction wins the first by construction: an extractive
answer IS the excerpt. So the proxy ranked ``answer-first-explained`` last, and
the RAG Triad later ranked it first.

Neither instrument was wrong. Using one of them for both dimensions was.

So every arm here is scored on both, and they are weighted equally because the
competition weights them equally:

    Triad answer relevancy   ->  answer accuracy   (25%)   key-free LLM judge
    cosine to key's sections ->  groundedness      (25%)   the grader's mechanism

What the arms are testing
-------------------------
**The hybrid.** A generated answer followed by the verbatim source text. The
generative arm gains +0.284 answer relevancy and loses groundedness because it
paraphrases. Appending the source restores lexical overlap without removing the
direct answer. If both dimensions can be held at once, that is worth more than
winning either.

**Length.** ``max_answer_chars=700`` was picked arbitrarily in Phase 3 and never
swept. The generative arm averages 440 characters, so the budget is barely
binding and the lever has never actually been pulled. The hybrid arms at 700 /
1000 / 1400 give the length curve for free, since concatenation is what makes
answers long enough for the budget to bite.

**Cost.** Every arm is built by concatenating answers already generated by
``sweep_answers.py``, so this pass generates nothing. Only the Triad judging
costs tokens.

Citations are frozen at the locked config throughout, so any arm here remains
directly submittable as a probe.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from proctoriq_rag.config import load_config  # noqa: E402
from proctoriq_rag.corpus.loader import load_corpus  # noqa: E402
from proctoriq_rag.evaluation.answer_key import load_answer_key  # noqa: E402
from proctoriq_rag.evaluation.scorer import Scorer  # noqa: E402
from proctoriq_rag.evaluation.triad import Eval  # noqa: E402
from proctoriq_rag.generation.cleaning import trim_to_budget  # noqa: E402
from proctoriq_rag.generation.groq_client import GroqChatClient, load_dotenv  # noqa: E402
from proctoriq_rag.pipeline import Pipeline, PipelineConfig  # noqa: E402
from proctoriq_rag.submission.writer import Prediction  # noqa: E402

KEY_PATH = REPO_ROOT / "data" / "validation" / "answer_key.yaml"
SWEEP_ANSWERS = REPO_ROOT / "outputs" / "answer_sweep_answers.json"

GENERATIVE = "D generative answer-first top2"
EXTRACT_1 = "A extractive top1 (SHIPPED)"
EXTRACT_2 = "B extractive top2"


def join(head: str, tail: str, budget: int) -> str:
    """Concatenate two answers and trim to budget, exactly as the pipeline would."""
    combined = " ".join(f"{head.strip()} {tail.strip()}".split())
    return trim_to_budget(combined, budget)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "outputs")
    parser.add_argument("--skip-triad", action="store_true",
                        help="groundedness only — free, no API calls")
    parser.add_argument("--all-arms", action="store_true",
                        help="include the arms the free pass already ruled out")
    args = parser.parse_args()

    load_dotenv(REPO_ROOT / ".env")
    config = load_config()
    corpus = load_corpus(config.paths.kb_dir)
    key = load_answer_key(KEY_PATH, corpus)
    kinds = {e.id: e.kind for e in key}

    questions = pd.read_csv(config.paths.test_csv)
    qids = questions["question_id"].astype(str).tolist()
    qtexts = questions["question"].astype(str).tolist()

    if not SWEEP_ANSWERS.exists():
        print(f"missing {SWEEP_ANSWERS} — run scripts/sweep_answers.py first")
        return 1
    blob = json.loads(SWEEP_ANSWERS.read_text(encoding="utf-8"))
    if blob["question_ids"] != qids:
        print("cached answers do not match test.csv question order")
        return 1
    cached = blob["answers"]

    print("reranking (citations frozen at the locked config) ...")
    pipeline = Pipeline(corpus=corpus, config=PipelineConfig())
    pipeline.fit(qtexts)
    citations = [pipeline.citations_for(i) for i in range(len(qtexts))]

    gen, ext1, ext2 = cached[GENERATIVE], cached[EXTRACT_1], cached[EXTRACT_2]

    # Order matters, and not for a stylistic reason: `trim_to_budget` cuts the
    # TAIL. Whichever half goes second is the half that gets truncated. The free
    # groundedness pass showed a complete extract is worth more than a complete
    # generated answer, so the extract-first arms keep the extract intact.
    arms: dict[str, list[str]] = {
        "A  extractive top1 (SHIPPED)":     list(ext1),
        "D  generative top2":               list(gen),
        "H1400  gen + extract@1400":        [join(g, e, 1400) for g, e in zip(gen, ext1)],
        "H2-1400 gen + extract(top2)@1400": [join(g, e, 1400) for g, e in zip(gen, ext2)],
        "P1000  extract + gen@1000":        [join(e, g, 1000) for g, e in zip(gen, ext1)],
        "P1400  extract + gen@1400":        [join(e, g, 1400) for g, e in zip(gen, ext1)],
        "P2-1400 extract(top2) + gen@1400": [join(e, g, 1400) for g, e in zip(gen, ext2)],
    }
    if args.all_arms:
        arms["D@300  generative, short budget"] = [trim_to_budget(a, 300) for a in gen]
        arms["H700   gen + extract@700"] = [join(g, e, 700) for g, e in zip(gen, ext1)]
        arms["H1000  gen + extract@1000"] = [join(g, e, 1000) for g, e in zip(gen, ext1)]

    print("loading embedder for the groundedness proxy ...")
    from sentence_transformers import SentenceTransformer

    scorer = Scorer(corpus, key,
                    embedder=SentenceTransformer(config.embedding.diagnostic_model))

    client = None if args.skip_triad else GroqChatClient()

    rows: list[dict] = []
    for name, texts in arms.items():
        print(f"\n=== {name} ===", flush=True)
        predictions = [
            Prediction(question_id=qid, answer_text=text,
                       cited_docs=[d for d, _ in cite],
                       cited_sections=[s for _, s in cite])
            for qid, text, cite in zip(qids, texts, citations)
        ]
        per_question = {q.question_id: q for q in scorer.score(predictions).per_question}

        relevancy: dict[str, float | None] = {qid: None for qid in qids}
        if client is not None:
            evaluator = Eval(client=client)
            print("  judging ...", flush=True)
            for i, qid in enumerate(qids):
                relevancy[qid] = evaluator.get_answer_relevancy(qtexts[i], texts[i], qid)
            if evaluator.unparseable:
                print(f"  unparseable: {len(evaluator.unparseable)}")

        for i, qid in enumerate(qids):
            rows.append({
                "arm": name, "question_id": qid, "kind": kinds[qid],
                "groundedness": per_question[qid].groundedness,
                "answer_relevancy": relevancy[qid],
                "chars": len(texts[i]),
            })
        frame = pd.DataFrame(rows)
        g = frame[frame.arm == name]
        print(f"  groundedness={g.groundedness.mean():.4f}  "
              f"answer_rel={g.answer_relevancy.mean():.4f}  chars={g.chars.mean():.0f}")

    frame = pd.DataFrame(rows)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    frame.to_csv(args.out_dir / "hybrid_sweep.csv", index=False)
    (args.out_dir / "hybrid_sweep_answers.json").write_text(
        json.dumps({"question_ids": qids, "answers": arms}, indent=2), encoding="utf-8"
    )
    _report(frame)
    return 0


def _report(frame: pd.DataFrame) -> None:
    rule = "=" * 104
    base_arm = next(a for a in frame.arm.unique() if a.startswith("A "))
    base = frame[frame.arm == base_arm]

    print("\n" + rule)
    print("HYBRID + LENGTH SWEEP — two instruments, equally weighted (25% each)")
    print(rule)
    print(f"  {'arm':<36} {'grounded':>9} {'answer rel':>11} "
          f"{'combined':>9} {'vs A':>8} {'chars':>7}")
    print("  " + "-" * 84)

    stats = (frame.groupby("arm", sort=False)
             .agg(grounded=("groundedness", "mean"),
                  answer_rel=("answer_relevancy", "mean"),
                  chars=("chars", "mean")))
    # Equal weights because the competition weights the two dimensions equally.
    stats["combined"] = stats[["grounded", "answer_rel"]].mean(axis=1)
    reference = stats.loc[base_arm, "combined"]
    for arm, row in stats.sort_values("combined", ascending=False).iterrows():
        marker = "  <-- shipped" if arm == base_arm else ""
        print(f"  {arm:<36} {row.grounded:>9.4f} {row.answer_rel:>11.4f} "
              f"{row.combined:>9.4f} {row.combined - reference:>+8.4f} "
              f"{row.chars:>7.0f}{marker}")

    print("\n" + rule)
    print("THE TRADE — where each instrument moves relative to the shipped arm")
    print(rule)
    for arm, row in stats.sort_values("combined", ascending=False).iterrows():
        if arm == base_arm:
            continue
        print(f"  {arm:<36} grounded {row.grounded - base.groundedness.mean():+.4f}   "
              f"answer_rel {row.answer_rel - base.answer_relevancy.mean():+.4f}")

    print("\n" + rule)
    print("LENGTH CURVE — combined score against mean answer length")
    print(rule)
    for arm, row in stats.sort_values("chars").iterrows():
        bar = "#" * int(round(row.combined * 60))
        print(f"  {row.chars:>6.0f} chars  {row.combined:.4f}  {bar}  {arm}")

    print("\n" + rule)
    print("BY KIND — combined score")
    print(rule)
    frame = frame.assign(combined=frame[["groundedness", "answer_relevancy"]].mean(axis=1))
    pivot = frame.pivot_table(index="arm", columns="kind", values="combined", aggfunc="mean")
    cols = [c for c in ("lookup", "adversarial", "multi_doc", "multi_section", "trap")
            if c in pivot.columns]
    print("  " + f"{'arm':<36}" + "".join(f"{c:>15}" for c in cols))
    print("  " + "-" * (36 + 15 * len(cols)))
    for arm in stats.sort_values("combined", ascending=False).index:
        line = f"  {arm:<36}"
        for c in cols:
            value = pivot.loc[arm, c]
            line += f"{value:>15.4f}" if not np.isnan(value) else f"{'-':>15}"
        print(line)

    print("\n  !! Two proxies, two different biases, neither calibrated to the grader.")
    print("     Groundedness uses a LOCAL embedding model (D-007); the grader's is unknown.")
    print("     Answer relevancy is an LLM judge — ordinal, valid for ranking arms only.")


if __name__ == "__main__":
    raise SystemExit(main())
